"""
Each new term in the Fibonacci sequence is generated by adding
the previous two terms. By starting with 1 and 2, the first 10
terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued terms.
"""
import sys


def even_fibonacci(n: int) -> int | str:
    prev, fib, sum = 0, 1, 0

    for _ in range(2, n + 1):
        if fib >= 4000000:
            return f"Term {fib} in Fibonacci sequence exceeds 4000000."
        prev, fib = fib, prev + fib
        if fib % 2 == 0:
            sum += fib
    return sum


# get n
n = abs(int(sys.argv[1])) if len(sys.argv) == 2 and sys.argv[1] else 1000

# n = 10 => 44
# n = 20 => 3382
# n = 100 => Term 5702887 in Fibonacci sequence exceeds 4000000.
print(even_fibonacci(n))
